FROM plexinc/pms-docker

LABEL image.version="1.0.0" \
      image.name="rev9en/plex" \
      image.description="Docker image with Plex" \
      image.date="2022-11-25" \
      maintainer="Evgen Rusakov" \
      url.docker="https://hub.docker.com/r/rev9en/plex" \
      url.source="https://github.com/revgen/docker/docker-plex"
