#!/usr/bin/env bash
# #
debug() { if [ "${DEBUG}" == "true" ]; then >&2 echo "$*"; fi }

image_name="${1}"
if [ -z "${image_name}" ] || [ "${image_name}" == "--help" ]; then
    echo "Usage: $(basename "${0}") <image name>"
    echo ""
    exit 1
fi
debug "Get ${image_name} tags"
curl -sL https://hub.docker.com/v2/repositories/${image_name}/tags?page_size=1000 \
| jq -r ".results[] | .name" | sort -rV
