#!/usr/bin/env bash
debug() { >&2 echo "$*"; }

src_dir="${1}"
if [ -z "${src_dir}" ] || [ "${src_dir}" == "--help" ]; then
    echo "Usage: $(basename "${0}") <directory with Dockerfile>"
    echo ""
    exit 1
fi
oldpwd="$(pwd)"

# Disable modern buildkit output
export DOCKER_BUILDKIT=0

debug "Build docker image"
cd "${src_dir}"
debug "Working directory is $(pwd)"
if [ ! -f "./Dockerfile" ]; then debug "Error: Dockerfile not found."; exit 1; fi

image_name=$(cat ./Dockerfile | grep "image.name" | cut -d'"' -f2)
image_version=$(cat ./Dockerfile | grep "image.version" | cut -d'"' -f2)
debug "Name   : ${image_name}"
debug "Version: ${image_version}"
if [ -z "${image_name}" ] || [ -z "${image_version}" ]; then
    debug "Error image name or/and version not found in the Dockerfile."; exit 1;
fi
debug "Building..."
docker build -t "${image_name}" ./ || exit 1
docker tag "${image_name}:latest" "${image_name}:${image_version}" || exit 1
debug "Done"
