name: Docker Image - Sandbox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-docker-sandbox:
    runs-on: ubuntu-latest
    name: "Build docker-sandbox"
    defaults:
      run:
        working-directory: ./docker-sandbox
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/sandbox
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Get docker image metadata
        continue-on-error: true
        run: |
          ../scripts/docker-check-image-version "${IMAGE_NAME}" || true
          ../scripts/docker-image-description "${IMAGE_NAME}" || true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: env.IMAGE_VERSION != env.REPO_IMAGE_VERSION
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        # Setting up Docker Buildx with docker-container driver is required
        # at the moment to be able to use a subdirectory with Git context
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: env.IMAGE_VERSION != env.REPO_IMAGE_VERSION
      - name: Build and push to the Docker Hub registry
        uses: docker/build-push-action@v3
        id: docker_build
        if: env.IMAGE_VERSION != env.REPO_IMAGE_VERSION
        with:
          context: "{{defaultContext}}:docker-sandbox"
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        if: env.IMAGE_VERSION != env.REPO_IMAGE_VERSION
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: ${{ env.IMAGE_DESCRIPTION }}
          readme-filepath: ./docker-sandbox/README.md
      - name: Build and push status
        if: success()
        run: |
          if [ "${IMAGE_VERSION}" != "${REPO_IMAGE_VERSION}" ]; then
            echo " * ${IMAGE_NAME}:${IMAGE_VERSION} - ${{ steps.docker_build.outputs.digest }}"
            echo "### :ok_hand: :white_check_mark: Docker image ${IMAGE_NAME}:${IMAGE_VERSION} was created!" >> $GITHUB_STEP_SUMMARY
          else
            echo "### :white_check_mark: Skip create docker image '${IMAGE_NAME}' version ${IMAGE_VERSION} already exists." >> $GITHUB_STEP_SUMMARY
          fi
